### ISSUE TITLE
Anyone was able to deploy Gonsul in Kubernetes?

### ISSUE THREAD

**Issue by marekprochaska** [miniclip/gonsul#32]
For me, it gives me a "REPO: reference not found" ERROR. I'm running this in Minikube, using the KVM2 driver. 
Note: In Docker-Compose, it works fine. The problem is only specific to Kubernetes or Minikube.
Here is my Gonsul Deployment definition:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gonsul
  name: gonsul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gonsul
  template:
    metadata:
      labels:
        app: gonsul
    spec:
      containers:
        - image: minicliposs/gonsul
          name: gonsul
          args: ["--consul-url=http://consul:8500", "--strategy=POLL", "--repo-url=https://github.com/marekprochaska/git2consul.git", "--repo-branch=main"]
          volumeMounts:
              - mountPath: /etc
                name: gonsul-volume
      volumes:
        - name: gonsul-volume
          hostPath:
            path: /data/gonsul
            type: Directory

```
And here is my Docker-Compose:
```
version: '3'
services:
  consul:
    image: consul
    container_name: consul01
    ports:
      - "8500:8500"
  gonsul:
    image: minicliposs/gonsul
    container_name: gonsul01
    command: ["--consul-url=http://consul:8500", "--strategy=POLL", "--repo-url=https://github.com/marekprochaska/git2consul.git", "--repo-branch=main"]
    depends_on:
      - "consul"
networks:
  default:
    external:
      name: gconsul_default
```
